sensio_framework_extra:
    view: { annotations: true }

fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: errors
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'html'], fallback_format: html, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
    param_fetcher_listener: true

    routing_loader:
        include_format: false
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
